### ISSUE TITLE
How do you read your table?

### ISSUE THREAD

**Issue by dkChase** [rviscomi/ismyhostfastyet#21]
What do the 3 colors represent? It would be a good idea if you let us know so we could understand the table without reading the entire page and then only guessing afterward.

Is the first number (green) mean that the website loads fast that percentage of the time?

Also, where are some of the more mainstream hosts: BlueHost Hostgator, Rackspace, DreamHost, etc?

**Comment by rviscomi** [comment]
Added threshold info to the table headers in #22 

![image](https://user-images.githubusercontent.com/1120896/80406874-bd415680-8892-11ea-9f5c-faee8547f019.png)

Any new hosts could be added manually if we're able to detect them. I'm not currently aware of any detection signals for these hosts.
