### ISSUE TITLE
Request: Add Bluehost

### ISSUE THREAD

**Issue by jkantner** [rviscomi/ismyhostfastyet#27]
Since I use Bluehost as my site host, I’d like it added to see how fast it is. Thanks!

**Comment by rviscomi** [comment]
Any ideas how to detect sites hosted on Bluehost?

**Comment by jkantner** [comment]
No clue how to detect any host, and I’m pretty sure using `whois` is off the table.

**Comment by rviscomi** [comment]
That's right, we effectively only have the network log (HTTP headers) and page content (HTML) to work with.
