### ISSUE TITLE
Move to Eleventy

### ISSUE THREAD

**Issue by dgrammatiko** [rviscomi/ismyhostfastyet#41]
I just created a repo https://github.com/dgrammatiko/ismyhostfast that
- uses eleventy for the website
- uses rollup for the compilation of js
- uses uhtml for the interactive table
- uses postcss for the css

The result is:
- Light mode
![Screenshot 2021-08-12 at 13 58 41](https://user-images.githubusercontent.com/3889375/129192975-ff754a30-a5a0-4d5b-a7fe-983236e8ecd7.png)

- Dark mode
![Screenshot 2021-08-12 at 13 58 52](https://user-images.githubusercontent.com/3889375/129193012-e4d9a2d7-4cea-489c-b6f2-d858dffce4e1.png)

- All table headers acting as selectors for sorting the table in descending order for the given header (the client is the only one with a select element with values: mobile, desktop, mobile and desktop)

You can fork the repo and do an `npm install` and then `npm run serve` to check it locally. For deployment, you will need to adjust the github pages to use the docs directory.
Let me know if there are any changes you want on the colours/layout/etc, and also if so I could spent some time cleaning up the css (there's way more css than what's needed here)...

Added a new view for a visual representation of the changes over time:
<img width="1307" alt="Screenshot 2021-08-15 at 23 20 42" src="https://user-images.githubusercontent.com/3889375/129493804-4d8a24d7-698b-442d-8c75-9bd7c587f2c7.png">

**Comment by rviscomi** [comment]
This is awesome, thanks so much for your help!

Do you have a staging link for me to test this out live?

**Comment by dgrammatiko** [comment]
I've published it using netlify: https://infallible-bhaskara-c439ba.netlify.app

**Comment by rviscomi** [comment]
Thanks! I really like the new UI. I've invited you to be a collaborator in this repo, so we can iterate together on the redesign in a separate branch/PR. Once you've accepted the invite, could you open a new branch with the code from your fork and start a PR? Then I'll start leaving comments in the code.

🍻

**Comment by dgrammatiko** [comment]
I already opened a draft PR: #42, so I guess I could close this one
