### ISSUE TITLE
MoM Historicals

### ISSUE THREAD

**Issue by carlisland** [rviscomi/ismyhostfastyet#85]
Is there a way to view historical results?  I'm over at WP Engine and it would be great to see MoM score movements as we push changes out on our platform.

**Comment by rviscomi** [comment]
Not in this report but you can see historical trends in the Core Web Vitals Tech Report (cwvtech.report). Here's an example using WP Engine (and some competitors on the Comparison tab): https://lookerstudio.google.com/s/tcPpYzlXrpM.

<img width="934" alt="image" src="https://github.com/rviscomi/ismyhostfastyet/assets/1120896/87536697-0e02-424f-84df-1d19027d834e">

<img width="943" alt="image" src="https://github.com/rviscomi/ismyhostfastyet/assets/1120896/1bbf50eb-a173-4aae-8deb-8662ee42237d">


The main difference between reports is the detection methodology. This one has a hard-coded [list](https://github.com/rviscomi/ismyhostfastyet/blob/5fd961ca694b00f2c89d69dc3dbc3f194c5d03bf/ttfb.sql#L5) of HTTP headers while the other is based on [Wappalyzer](https://github.com/HTTPArchive/wappalyzer). The other has a lot more functionality like the ability to slice by site rank and user geo, if useful.

**Comment by carlisland** [comment]
Thanks for the response! Very helpful
